/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"DM Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        heebo: ['Heebo', 'system-ui', 'sans-serif'],
      },
      colors: {
        // Stitch tonal color system
        'primary': '#005bc4',
        'primary-dim': '#004fad',
        'primary-fixed': '#4388fd',
        'primary-fixed-dim': '#317bef',
        'primary-container': '#4388fd',
        'on-primary': '#f9f8ff',
        'on-primary-container': '#000311',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#001435',
        'inverse-primary': '#4d8eff',
        'secondary': '#575f72',
        'secondary-dim': '#4b5366',
        'secondary-container': '#dbe2f9',
        'secondary-fixed': '#dbe2f9',
        'secondary-fixed-dim': '#cdd4eb',
        'on-secondary': '#f9f8ff',
        'on-secondary-container': '#4a5264',
        'on-secondary-fixed': '#383f51',
        'on-secondary-fixed-variant': '#545b6e',
        'tertiary': '#695781',
        'tertiary-dim': '#5d4b74',
        'tertiary-container': '#e4ceff',
        'tertiary-fixed': '#e4ceff',
        'tertiary-fixed-dim': '#d6c0f0',
        'on-tertiary': '#fef6ff',
        'on-tertiary-container': '#54436b',
        'on-tertiary-fixed': '#413057',
        'on-tertiary-fixed-variant': '#5e4c75',
        'surface': '#f7f9fb',
        'surface-dim': '#d4dbdf',
        'surface-bright': '#f7f9fb',
        'surface-tint': '#005bc4',
        'surface-variant': '#dce4e8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4f7',
        'surface-container': '#eaeff2',
        'surface-container-high': '#e3e9ed',
        'surface-container-highest': '#dce4e8',
        'on-surface': '#2c3437',
        'on-surface-variant': '#596064',
        'on-background': '#2c3437',
        'inverse-surface': '#0b0f10',
        'inverse-on-surface': '#9a9d9f',
        'outline': '#747c80',
        'outline-variant': '#acb3b7',
        'background': '#f7f9fb',
        'error': '#a83836',
        'error-dim': '#67040d',
        'error-container': '#fa746f',
        'on-error': '#fff7f6',
        'on-error-container': '#6e0a12',
      },
    },
  },
  plugins: [],
}
